### ISSUE TITLE
Error: Registry returned 404 for GET on https://registry.npmjs.org/cordova-plugin-memory-alert

### ISSUE THREAD

**Issue by ghost** [88dots/cordova-plugin-memory-warning#1]
I am getting following issue during plugin add:

Error: Registry returned 404 for GET on https://registry.npmjs.org/cordova-plugin-memory-alert

**Comment by collinhover** [comment]
@amitds try "cordova-plugin-memory-**warning**" at https://registry.npmjs.org/cordova-plugin-memory-warning
